name: Dart

on:
  push:
    branches: [ "mistress" ]
  pull_request:
    branches: [ "mistress" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos
 
 #     - name: Run tests
 #       run: dart test
